# Adapté de meta-rockchip recipes-graphics/xorg-xserver/files/20-modesetting.conf
Section "Device"
    Identifier  "Rockchip Graphics"
    Driver      "modesetting"
    Option      "AccelMethod"    "glamor"
    Option      "DRI"            "2"
    Option      "FlipFB"         "always"
EndSection
Section "Screen"
    Identifier  "Default Screen"
    Device      "Rockchip Graphics"
EndSection
